apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: metrics
      department: software-avanzado
  replicas: 1
  template:
    metadata:
      labels:
        app: metrics
        department: software-avanzado
    spec:
      containers:
      - name: frontend-sa
        image: edson2021/frontend
        ports:
        - containerPort: 80