apiVersion: v1
kind: Service
metadata:
  name: sa-front-service
spec:
  type: NodePort
  selector:
    app: metrics
    department: software-avanzado
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80